# Generated by Django 3.2.5 on 2021-09-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_category_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='cat_Name',
            field=models.CharField(max_length=50),
        ),
    ]
